version: '3.8'

services:
  shopping-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - BACKEND_URL=http://localhost:3000   # neu beschrieben mit URl wenn container gestartet wird ? 
    depends_on:
      - backend-service

  #backend-service:
  #  image: your-backend-image
  #  ports:
  #    - "5000:5000"
  #  environment:
  #    - NODE_ENV=development